// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NameAPIProxyService.Data;

#nullable disable

namespace HelloMD.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloMD.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 21, 11, 51, 28, 716, DateTimeKind.Local).AddTicks(2364),
                            FirstName = "Zerihun",
                            LastName = "H.",
                            LastSeen = new DateTime(2023, 1, 21, 11, 51, 28, 716, DateTimeKind.Local).AddTicks(2293),
                            Password = "test",
                            UpdatedAt = new DateTime(2023, 1, 21, 11, 51, 28, 716, DateTimeKind.Local).AddTicks(2369),
                            Username = "zeru"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 21, 11, 51, 28, 716, DateTimeKind.Local).AddTicks(2384),
                            FirstName = "loine",
                            LastName = "K.",
                            LastSeen = new DateTime(2023, 1, 21, 11, 51, 28, 716, DateTimeKind.Local).AddTicks(2380),
                            Password = "test",
                            UpdatedAt = new DateTime(2023, 1, 21, 11, 51, 28, 716, DateTimeKind.Local).AddTicks(2387),
                            Username = "loli"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
